### ISSUE TITLE
Next-gen підсистема тестування і оцінювання розв'язків

### ISSUE THREAD

**Issue by sirkadirov** [overtest/overtest#2]
Настав час повністю перебудувати **Overtest Verification Agent** - серверний застосунок, який обробляє запити на перевірку розв'язків до завдань, компілює, тестує і оцінює їх згідно з критеріями, вказаними автором кожного окремого завдання. Разом з ним, на великі зміни чекають набір бібліотек та інтерфейсів `Overtest TestLib`, бібліотека [`Project LIMTRAC`](https://github.com/overtest/limtrac) та інші складові частини проєкту **Overtest**. Це необхідно зробити для подальшої можливості розширення функціоналу всієї системи, а також оптимізації її роботи, серед іншого, у масштабованих середовищах.

### Процес виконання
- [x] Розробка архітектури серверного застосунку `Overtest Verification Agent`
- [x] Підвантаження конфігурації застосунку і підтримуваних компіляторів
  - [x] Підвантаження конфігурації застосунку (з JSON-файлу)
  - [x] `Singleton`-сервіс підвантаження підтримуваних компіляторів
- [x] Підтримувані агентом тестування компілятори
  - [x] Розробка API для створення нових компіляторів на основі `Lua`-скриптингу
  - [x] Зберігання, обробка та використання інформації про підтримувані компілятори
  - [x] Обмеження відбору запитів на тестування тільки підтримуваними компіляторами
- [x] Функціонал кешування даних, необхідних для тестування розв'язків
  - [x] `Singleton`-сервіс кешування і доступу до `VerificationData`
  - [x] Можливість оновлення `VerificationData` для усіх завдань
  - [x] Можливість оновлення `VerificationData` для одного із завдань
  - [x] Функціонал для отримання `VerificationData` для одного із завдань
  - [x] Можливість видалення усіх застарілих `VerificationData` під час запуску
- [x] Створення базового алгоритму відбору запитів на тестування
- [x] Реалізація функціоналу бібліотеки `TestLib`
  - [x] `Generators` - Підтримка стандартних і користувацьких програм-генераторів тестів
  - [x] `Checkers` - Підтримка стандартних і користувацьких програм оцінювання
  - [x] #5
- [x] Реалізація процесу тестування і оцінювання розв'язків
  - [x] **Етап тестування №1:** Компіляція розв'язку користувача у виконувану програму
  - [x] **Етап тестування №2:** Оцінювання результатів компіляції програми користувача
  - [x] **Етап тестування №3:** Тестування розв'язку у ізольованому середовищі
    - [x] `Syntax mode` - Режим перевірки синтаксису
    - [x] `Release mode` - Режим фінального тестування і оцінювання розв'язків
    - [x] Бібліотека для запуску користувацьких програм із заданими обмеженнями
  - [x] **Етап тестування №4:** Фінальне оцінювання результатів тестування розв'язку

### Корисні матеріали
- [Dependency injection techniques in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection)
- [.NET Generic Host: IHostApplicationLifetime](https://docs.microsoft.com/en-us/dotnet/core/extensions/generic-host#ihostapplicationlifetime)
- [Background tasks with hosted services in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services)

**Comment by sirkadirov** [comment]
У зв'язку із закінченням роботи над більшою частиною сервісів і функціоналу `Overtest Web Application` (про що свідчить статус #3) починаю роботу над даним завданням. За потреби, буду доопрацьовувати сервіси вебзастосунку системи.

**Comment by sirkadirov** [comment]
```c#
2021-11-17 00:41:10.3284|OVerificationAgent.HostedServices.VerificationQueueHostedService|ERROR|#2: An exception caught during the verification process: Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have bee
n modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at OVerificationAgent.VerificationProcess.VerificationProcessBuilder.UploadVerificationResultsAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\VerificationProcess\VerificationProcessBuilder.cs:line 150
   at OVerificationAgent.VerificationProcess.VerificationProcessBuilder.ExecuteAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\VerificationProcess\VerificationProcessBuilder.cs:line 196
   at OVerificationAgent.HostedServices.VerificationQueueHostedService.ExecuteVerificationCycleAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\HostedServices\VerificationQueueHostedService.cs:line 168
   at OVerificationAgent.HostedServices.VerificationQueueHostedService.ExecuteVerificationCycleAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\HostedServices\VerificationQueueHostedService.cs:line 176 CurrentTaskId=2
```

**Comment by sirkadirov** [comment]
Реалізаціюю режиму тестування розв'язків `SyntaxMode` успішно завершено. У зв'язку з цим, у вебзастосунок системи необхідно внести можливість відображення результатів виконання цього режиму тетування #3.

**Comment by sirkadirov** [comment]
Підтримка програм-ініціалізаторів та програм-фіналізаторів бібліотеки `TestLib` системи буде імплементовано у наступних версіях Overtest у зв'язку з обмеженими можливостями для їх використання на даному етапі розвитку проєкту.

**Comment by sirkadirov** [comment]
```C#
2021-11-17 22:23:50.9468|OVerificationAgent.HostedServices.VerificationQueueHostedService|INFO|#2: Starting verification of '08d9aa08-2b16-4b9b-88ea-ca2255d155fa'... CurrentTaskId=2, TaskSolutionId=08d9aa08-2b16-4b9b-88ea-ca2255d155fa
2021-11-17 22:23:50.9468|OVerificationAgent.VerificationProcess.VerificationProcessBuilder|DEBUG|"VerificationProcessBuilder" for task solution '08d9aa08-2b16-4b9b-88ea-ca2255d155fa' created, waiting for commands... ObjectType=VerificationProcessBuilder, TaskSolutionId=08d9aa08-2b16-4b9b-88ea-ca2255d155fa
2021-11-17 22:23:50.9468|OVerificationAgent.VerificationProcess.VerificationProcessBuilder|DEBUG|"ExecuteAsync": Starting verification process of '08d9aa08-2b16-4b9b-88ea-ca2255d155fa'... MethodName=ExecuteAsync, TaskSolutionId=08d9aa08-2b16-4b9b-88ea-ca2255d155fa
2021-11-17 22:23:50.9468|OVerificationAgent.VerificationProcess.VerificationProcessBuilder|DEBUG|08d9aa08-2b16-4b9b-88ea-ca2255d155fa': Initializing... TaskSolutionId=08d9aa08-2b16-4b9b-88ea-ca2255d155fa
2021-11-17 22:23:50.9582|OVerificationAgent.VerificationProcess.VerificationProcessBuilder|DEBUG|08d9aa08-2b16-4b9b-88ea-ca2255d155fa': Starting execution of pre-built verification process task... TaskSolutionId=08d9aa08-2b16-4b9b-88ea-ca2255d155fa
4
2021-11-17 22:23:50.9582|OVerificationAgent.SingletonServices.TasksDataCachingService|DEBUG|UnsafeDownloadUpdatedDataStorageAsync: Trying to update cache for programming task 'fe50ba2f-8b75-4714-8bfc-a315612d7f8a'... MethodName=UnsafeDownloadUpdatedDataStorageAsync, ProgrammingTaskId=fe50ba2f-8b75-4714-8bfc-
a315612d7f8a
2021-11-17 22:23:50.9582|OVerificationAgent.SingletonServices.TasksDataCachingService|DEBUG|UnsafeDownloadUpdatedDataStorageAsync: Cache for programming task 'fe50ba2f-8b75-4714-8bfc-a315612d7f8a' is up to date! MethodName=UnsafeDownloadUpdatedDataStorageAsync, ProgrammingTaskId=fe50ba2f-8b75-4714-8bfc-a3156
12d7f8a
5
2021-11-17 22:23:51.1649|OVerificationAgent.VerificationProcess.VerificationProcessBuilder|DEBUG|08d9aa08-2b16-4b9b-88ea-ca2255d155fa': Execution of pre-built verification process task finished! TaskSolutionId=08d9aa08-2b16-4b9b-88ea-ca2255d155fa
2021-11-17 22:23:51.1960|OVerificationAgent.HostedServices.VerificationQueueHostedService|ERROR|#2: An exception caught during the verification process: System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command) in /_/src/MySqlConnector/Core/ServerSession.cs:line 294
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 54
   at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 271
   at MySqlConnector.MySqlConnection.BeginTransactionAsync(IsolationLevel isolationLevel, Nullable`1 isReadOnly, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 179
   at MySqlConnector.MySqlConnection.BeginDbTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 132
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at OVerificationAgent.VerificationProcess.VerificationProcessBuilder.UploadVerificationResultsAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\VerificationProcess\VerificationProcessBuilder.cs:line 224
   at OVerificationAgent.VerificationProcess.VerificationProcessBuilder.ExecuteAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\VerificationProcess\VerificationProcessBuilder.cs:line 288
   at OVerificationAgent.HostedServices.VerificationQueueHostedService.ExecuteVerificationCycleAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\HostedServices\VerificationQueueHostedService.cs:line 168
   at OVerificationAgent.HostedServices.VerificationQueueHostedService.ExecuteVerificationCycleAsync(CancellationToken cancellationToken) in Z:\ngosupremeorder\overtest\ServerApplications\OVerificationAgent\HostedServices\VerificationQueueHostedService.cs:line 175 CurrentTaskId=2
```

**Comment by sirkadirov** [comment]
### Приклад плагіну компіляції (для мови програмування Free Pascal)
```Lua
-- Common language runtime imports
import("System.IO")
import("System.Runtime.InteropServices")
-- Importing namespaces listed below is required
-- to make the compiler plugin work correctly.
import("Overtest.SharedLibraries.ProgrammingTasksShared.SupportedCompilers")

-- Compiler plugin configuration section
compiler_full_path = "C:/Program Files/FreePascal/bin/i386-win32/fpc.exe" -- Full path to the compiler or command name
compiler_arguments = "source.pas -l -Px86_64 -vewnhilq" -- Compiler arguments (with information about source files)
compiled_executable_name = "source" -- Executable file name without extension dependant on compiler arguments

-- Function that helps compile source code into an executable program.
function Compile(sources_directory)
    -- Use default compiler execution method and get execution results
    local compilerExecutionResult = CompilationMethods:ExecuteCompiler(
        compiler_full_path,
        compiler_arguments,
        sources_directory)
    -- Use default method to form the compilation result
    return CompilationMethods:FormDefaultCompilationResult(compilerExecutionResult, 0)
end

-- Returns a full path to the main source code file. This
-- file will be created by Overtest Verification Agent.
function GetSourceCodeFileFullPath(sources_directory)
    return Path.Combine(sources_directory, compiled_executable_name .. ".pas")
end

-- This function returns process execution parameters
-- for programs, written in the programming language,
-- supported by the current compilation plugin.
function GetExecutionParams(sources_directory, arguments)
    -- Create a new instance of ExecutionParameters CLR class
    local execParams = ExecutionParameters()
    -- Set executable file name (file name extension depends on platform)
    if RuntimeInformation.IsOSPlatform(OSPlatform.Windows) then -- Platform is Windows
        execParams.ExecutableFullName = Path.Combine(sources_directory, compiled_executable_name .. ".exe")
    else -- Platform is GNU/Linux (or compatible)
        execParams.ExecutableFullName = Path.Combine(sources_directory, compiled_executable_name)
    end
    -- Set command line arguments for executable
    execParams.Arguments = arguments
    -- Return execution parameters
    return execParams
end
```
### Приклад генератора (копіювання файлів зі вхідними даними)
```Lua
-- Default test generator
-- ======================
-- This generator copies input data from the task's verification
-- data into the specified output directory. See documentation for
-- more information about how to use generators and checkers.

-- Common language runtime imports
import("System.IO")

-- Generator configuration section
tests_directory_name = "tests"
tests_input_data_directory_name = "input"

function GenerateTest(test_id, verification_data_directory, output_directory)
    -- Use test data for test #1 as the
    -- debug verification mode input data.
    if test_id == -1 then
        test_id = 1
    end
    -- Generate input data path
    local source_dir = Path.Combine(
        verification_data_directory,
        tests_directory_name,
        tests_input_data_directory_name,
        tostring(test_id)
    )
    -- Check whether input data path exists.
    -- If not, return 'false' to the caller.
    if not Directory.Exists(source_dir)
        return false
    end
    -- Copy all contents of the input data
    -- directory into the specified output path.
    PlaceTestInputData(source_dir, output_directory)
    -- Generation succeeded, so return true to the caller
    return true
end

function PlaceTestInputData(source_dir, destination_dir)
    OvertestSharedMethods_FS_SecureCopyDirectory(source_dir, destination_dir)
end
```

**Comment by sirkadirov** [comment]
Виконання завершено успішно.
